#spring:
#  application:
#    name: internal-cache
#  kafka:
#    producer:
#      batch-size: 200
#      bootstrap-servers: localhost:9092
#      retries: 3
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#logging:
#  config: classpath:log4j2.xml
